spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_db?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: xiejunxi520
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9090
